replicaCount: 2
dbReplicaCount : 1

image:
  repository: salilr/study_app
  pullPolicy: IfNotPresent
  tag: "v54"

imagePullSecrets: 
  - name: dockerhubsalil

service:
  dbType: ClusterIP
  appType: NodePort
  port: 80
  appPort: 5000
  dbPort: 6380
  nodeport: 35000

resources: 
  requests:
    cpu: 2m
    memory: 100Mi

tolerations: 
  - key: "app"
    value: "helm"
    effect: "NoSchedule"
    condition: "Equals"

